services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile:  ./php/Dockerfile
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
      - ./logs/php-fpm:/var/log/php-fpm
      - ./docker/php-fpm:/usr/local/etc/php-fpm.d
    working_dir: /var/www/html
    command: ["php-fpm", "-F"]

  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
